{% set name = "fitsio" %}
{% set version = "1.1.9" %}
{% set sha256 = "fb4eac699c9310ee3df2c604d031053d1625ad1f16f4377e1a8f3ea02298b522" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - libtool  # [unix]
    - {{ compiler('c') }}
    - make
  host:
    - python
    - pip
    - numpy
    - bzip2
    - libcurl
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - bzip2
    - setuptools  # the test modules now use pkg_resources

test:
  imports:
    - fitsio
  commands:
    - python -c "import fitsio; fitsio.test.test()"

about:
  home: https://github.com/esheldon/fitsio
  license: GPL-2.0-only
  license_file:
    - LICENSE.txt
    - LICENSE_cfitsio.txt
  summary: A python library to read from and write to FITS files.
  description: |
    This is a python extension written in c and python. Data are read into
    numerical python arrays. A version of cfitsio is bundled with this package,
    there is no need to install your own, nor will this conflict with a
    version you have installed.
  doc_url: https://github.com/esheldon/fitsio
  dev_url: https://github.com/esheldon/fitsio

extra:
  recipe-maintainers:
    - beckermr
